### ISSUE TITLE
Tooltip is not working

### ISSUE THREAD

**Issue by blpcastanheira** [N1ghtly/react-native-responsive-linechart#33]
I'm trying to use tooltip in my chart but its not working.
The chart is shown, but the tooltip is never displayed.
Can you check the chart in demo project? Its not working for me.

Ty

**Comment by N1ghtly** [comment]
Hi @blpcastanheira, I have just checked it and it appears to be working fine. Are you sure you're using the correct chart? Only the 4th one in the Demo application has tooltips enabled.

**Comment by blpcastanheira** [comment]
Hey @N1ghtly,

I copied this chart (https://github.com/N1ghtly/react-native-responsive-linechart/blob/85cd0672bdfba567048b4bfb4428c6fe7786cb94/demo/App.tsx#L104) from App.tsx.

I'm using the version 5.1.0 and running on Android. I can't test this on iOS.

Ty

**Comment by blpcastanheira** [comment]
Can you replicate the issue?

**Comment by N1ghtly** [comment]
Yes I was able to replicate it. It turns out to be a rather simple mistake: the demo project did not complete the installation steps for `react-native-gesture-handler` correctly. Have a look at https://docs.swmansion.com/react-native-gesture-handler/docs/#android. I'm 99% sure that should solve your problem :)

**Comment by blpcastanheira** [comment]
It worked!!
Ty bro :100:

**Comment by N1ghtly** [comment]
Great, closing 🥳
